{
  "01": {
    "config": {
      "Maya_executable": {
        "Maya_2016": "/usr/autodesk/maya2016/bin/Render",
        "Maya_2015": "/usr/autodesk/maya2015-x64/bin/Render",
        "Maya_2014": "/usr/autodesk/maya2014-x64/bin/Render",
        "Maya_2013": "/usr/autodesk/maya2013-x64/bin/Render"
      },
      "Maya_renderer": {
        "mentalray": "mr",
        "maya_software": "sw",
        "maya_hardware": "hw",
        "maya_file": "file",
        "vray": "vray",
        "3Delight": "3Delight",
        "arnold": "arnold"
      },
      "chunksize": "10",
      "priority": "100",
      "dispatcher":{
        "localbatch":{
          "maya":"test"
        }
      },
      "Nuke_executable": {
        "Nuke_2016": "/usr/autodesk/maya2016/bin/Render",
        "Nuke_2015": "/usr/autodesk/maya2015-x64/bin/Render",
        "Nuke_2014": "/usr/autodesk/maya2014-x64/bin/Render",
        "Nuke_2013": "/usr/autodesk/maya2013-x64/bin/Render"
      },
      "jobNameTemplate":"<filename>",

##      "Qube6": {
##        "dispatch_software": "Qube6",
##        "dispatch_manager": "localhost.localdomain",
##        "submitter":"/usr/local/pfx/qube/bin/qbsub"
##      },
##      "Deadline7":{
##          "dispatch_software": "Deadline7",
##          "repository": "/DeadlineRepository7",
##          "submitter": ""
##      }
##      }
#        "use_dispatcher":["Qube6"],

      ## Studio Setting
      "dispatcher_default":"Qube6",
      "priority":"9999"
    }
  }
}