{
  "01": {
    "auto_config_overwrite": {
      "Maya_executable": {
        "Maya_2016": "/usr/autodesk/maya2016/bin/Render",
        "Maya_2015": "/usr/autodesk/maya2015-x64/bin/Render",
        "Maya_2014": "/usr/autodesk/maya2014-x64/bin/Render",
        "Maya_2013": "/usr/autodesk/maya2013-x64/bin/Render"
      },
      "Maya_renderer": {
        "mentalray": "mr",
        "maya_software": "sw",
        "maya_hardware": "hw",
        "maya_file": "file",
        "vray": "vray",
        "3Delight": "3Delight"
      },
      "chunksize": "10",
      "priority": "100"
##    "dispatcher":{
##      "Qube6": {
##        "dispatch_software": "Qube6",
##        "dispatch_manager": "localhost.localdomain",
##        "submitter":"/usr/local/pfx/qube/bin/qbsub"
##      },
##      "Deadline7":{
##          "dispatch_software": "Deadline7",
##          "repository": "/DeadlineRepository7",
##          "submitter": ""
##      }
##      }
    }
  },
  "99":{
      "studio_setting":{
        "use_dispatcher":["Qube6"],
        "priority":"9999"
      }
  }
}